apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: http-filter-redirect
  namespace: test-suth
spec:
  parentRefs:
    - name: redirect-gateway
      sectionName: http
  hostnames:
    - test-suth.c8f1d33.kyma.ondemand.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
